plugins {
    id 'base'
    id 'maven-publish'
}

group = 'com.perkox'
version = project.hasProperty('version') && project.version != 'unspecified' ? project.version : '1.0.4'

publishing {
    publications {
        maven(MavenPublication) {
            groupId = project.hasProperty('group') ? project.group : 'com.perkox'
            artifactId = 'perkox-android-sdk-releases'
            version = project.version

            artifact(file("perkox-android-sdk-release.aar")) {
                extension = 'aar'
            }

            pom.withXml {
                def dependenciesNode = asNode().appendNode('dependencies')

                def appcompat = dependenciesNode.appendNode('dependency')
                appcompat.appendNode('groupId', 'androidx.appcompat')
                appcompat.appendNode('artifactId', 'appcompat')
                appcompat.appendNode('version', '1.6.1')
                appcompat.appendNode('scope', 'runtime')

                def coreKtx = dependenciesNode.appendNode('dependency')
                coreKtx.appendNode('groupId', 'androidx.core')
                coreKtx.appendNode('artifactId', 'core-ktx')
                coreKtx.appendNode('version', '1.10.1')
                coreKtx.appendNode('scope', 'runtime')
            }
        }
    }
}
