plugins {
    id 'base'
    id 'maven-publish'
}

group = 'com.perkox'
version = project.hasProperty('version') && project.version != 'unspecified' ? project.version : '2.0.3'

publishing {
    publications {
        maven(MavenPublication) {
            groupId = project.hasProperty('group') ? project.group : 'com.perkox'
            artifactId = 'perkox-android-sdk-releases'
            version = project.version

            artifact(file("perkox-android-sdk-release.aar")) {
                extension = 'aar'
            }

            pom.withXml {
                def dependenciesNode = asNode().appendNode('dependencies')

                def coreKtx = dependenciesNode.appendNode('dependency')
                coreKtx.appendNode('groupId', 'androidx.core')
                coreKtx.appendNode('artifactId', 'core-ktx')
                coreKtx.appendNode('version', '1.10.1')
                coreKtx.appendNode('scope', 'runtime')

                def playServicesAds = dependenciesNode.appendNode('dependency')
                playServicesAds.appendNode('groupId', 'com.google.android.gms')
                playServicesAds.appendNode('artifactId', 'play-services-ads-identifier')
                playServicesAds.appendNode('version', '18.2.0')
                playServicesAds.appendNode('scope', 'runtime')
            }
        }
    }
}
